services:
  greedy-api:
    image: ghcr.io/rustxpy/greedy:main
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped

networks:
  default:
    name: greedy-test-net
